name: Github Action demo

on: 
  push:
    branches: 
      - main 
  pull_request: 
    branches: 
      - 'main'
env:
  MY_HOST: '127.0.0.1'
  COMPANY_NAME: 'CCT'

jobs:
  build-job:
    runs-on: ubuntu-latest
    env:
      FULLNAME: 'John Doe'
    steps:
      - run: echo "my host is $MY_HOST and $FULLNAME"
      - run: echo "Repo ${{ github.actor }} ${{ github.ref }} $FULLNAME"
      - run: echo "vars Company name > ${{ vars.COMPANY_NAME }} "
      - run: echo "env Company name > ${{ env.COMPANY_NAME }}"
      - run: echo "Company name > $COMPANY_NAME"
      - run: echo "secret company ${{ secrets.MYSQL_PASSWORD }}"
  test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - run: echo "test job Repo is ${{ github.repository }} my host ${{ env.MY_HOST }}"
  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - run: echo "deploy job to production server ${{ job.status }}"