name: Github Action demo

on: 
  push:
    branches: 
      - main 
  pull_request: 
    branches: 
      - 'main'
  

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Repo ${{ github.actor }} ${{ github.ref }} "
  test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - run: echo "test job Repo is ${{ github.repository }}"
  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - run: echo "deploy job to production server ${{ job.status }}"